### ISSUE TITLE
Langage MySQL 

### ISSUE THREAD

**Issue by vincent-agi** [kyoshiroDev/Mon-portfolio#1]
Bonjour, si je peux me permettre une suggestion de modification MySQL n'est pas un langage mais un sgbdr. Je suppose que vous parlez plutôt du langage SQL ?
Cordialement

**Comment by kyoshiroDev** [comment]
Bonjours, oui effectivement merci de relever cette erreur de ma part
Cordialement

**Comment by vincent-agi** [comment]
Bonjour monsieur,
ici : src/app/components/about-us/about-us.component.html

ligne 11

cordialement

**Comment by kyoshiroDev** [comment]
À OK, je cherchais dans le code mdr pas le texte merci beaucoup

**Comment by vincent-agi** [comment]
Avec plaisir :). Si vous avez réglé le suggestion peut-être peut-on close cette issue ?
